version: '2'
 
services:
    sshbastion:
        image: sshbastion
        ports:
            - 2200:2200
        restart: always
 
    reverseproxy:
        image: reverseproxy
        ports:
            - 80:80
            - 443:443
        restart: always
        # map default certificate and dh file for NAS into nginx container
        # for ease of certificate management.
        volumes:
            - /usr/syno/etc/certificate/system/default:/etc/ssl
            - /usr/syno/etc/ssl/dh2048.pem:/etc/ssl/dh2048.pem
 
    sabnzbd:
        depends_on:
            - reverseproxy
        image: linuxserver/sabnzbd:latest
        restart: always
        volumes:
            - /volume1/mediatools/sabnzbd/incomplete-downloads:/incomplete-downloads
            - /volume1/Media:/downloads
            - /volume1/mediatools/sabnzbd/config:/config
        environment:
            - TZ=PST8PDT
            - PUID=1027
            - PGID=65536
 
    sonarr:
        depends_on:
            - reverseproxy
        image: linuxserver/sonarr:latest
        restart: always
        volumes:
            - /volume1/Media:/tv
            - /volume1/Media:/downloads
            - /volume1/mediatools/sonarr:/config
        environment:
            - TZ=PST8PDT
            - PUID=1027
            - PGID=65536
        
    radarr:
        depends_on:
            - reverseproxy
        image: linuxserver/radarr:latest
        restart: always
        volumes:
            - /volume1/Media/Movies:/movies
            - /volume1/Media:/downloads
            - /volume1/mediatools/radarr:/config
        environment:
            - TZ=PST8PDT
            - PUID=1027
            - PGID=65536
        
    couchpotato:
        depends_on:
            - reverseproxy
        image: linuxserver/couchpotato:latest
        restart: always
        volumes:
            - /volume1/Media/Movies:/movies
            - /volume1/Media/00-UsenetIncoming:/downloads
            - /volume1/mediatools/couchpotato:/config
        environment:
            - TZ=PST8PDT
            - PUID=1027
            - PGID=65536
 
    moinmoin:
        depends_on:
            - reverseproxy
        image: moinmoin:latest
        restart: always
        volumes:
            - /volume1/mediatools/moin:/moin
        environment:
            - TZ=PST8PDT
            - PUID=1027
            - PGID=65536

    tautulli:
        depends_on:
            - reverseproxy
        image: linuxserver/tautulli:latest
        restart: always
        ports:
            - 8181:8181
        volumes:
            - /volume1/Plex/Library/Logs:/logs:ro
            - /volume1/mediatools/tautulli:/config
        environment:
            - TZ=PST8PDT
            - PUID=1027
            - PGID=65536

    transmission:
        depends_on:
            - reverseproxy
        image: linuxserver/transmission:latest
        restart: always
        ports:
            - 51413:51413
        volumes:
            - /volume1/Media/Torrents:/downloads
            - /volume1/Media/Torrents/watch:/watch
            - /volume1/mediatools/transmission:/config
        environment:
            - TZ=PST8PDT
            - PUID=1027
            - PGID=65536


